server.port=8081
spring.application.name=catalogue-service

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://postgres-catalogue:5432/cataloguedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=catalogue_user
spring.datasource.password=catalogue_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka et Management
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
management.endpoints.web.exposure.include=*
