server.port=8082
spring.application.name=commande-service

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://postgres-commande:5432/commandedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=commande_user
spring.datasource.password=commande_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka et Management
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
management.endpoints.web.exposure.include=*
