server.port=8083
spring.application.name=paiement-service

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://postgres-paiement:5432/paiementdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=paiement_user
spring.datasource.password=paiement_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka et Management
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
management.endpoints.web.exposure.include=*
