server.port=8081
spring.application.name=catalogue-service

# --- Base de données PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/service1db
spring.datasource.username=service1user
spring.datasource.password=service1pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Eureka ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# --- Actuator & Logs ---
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.level.com.example.catalogue_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
