apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiement-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: paiement-service
  template:
    metadata:
      labels:
        app: paiement-service
    spec:
      containers:
      - name: paiement-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service-paiement:5432/service2db
        - name: SPRING_DATASOURCE_USERNAME
          value: service1user
        - name: SPRING_DATASOURCE_PASSWORD
          value: service1pass
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://discovery-service:8761/eureka
        volumeMounts:
        - name: postgres-storage
          mountPath: /data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
